### ISSUE TITLE
Parts

### ISSUE THREAD

**Issue by fi0** [yskoht/thumbhelix_device#1]
Hi - can you let me know the part number of the joystick please? Thank you!

**Comment by yskoht** [comment]
@fi0

Thank you for asking! The part number is this.

```
Top-Up Industry Corporation
JT8P-3.2T-B10K-1-16Y
```

Datasheet is here.
http://www.top-up.com.tw/front/bin/ptdetail.phtml?Part=JT8P-32T

See also the following article, if you want. (Sorry in Japanese...)
https://yskoht.hatenablog.com/entry/2018/05/01/011027

**Comment by fi0** [comment]
Thank you!
